[build]
  # Build komutu (statik site için gerekli değil)
  command = "cd netlify/functions && npm install"
  # Publish edilecek klasör
  publish = "."
  # Functions klasörü
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  # Local development
  command = "npx netlify dev"
  port = 8888

# Environment variables (Netlify Dashboard'dan eklenecek)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
