name: Send Daily Report

on:
  schedule:
    # Her saat başı çalışır: 09:00-18:00 Turkish Time (06:00-15:00 UTC)
    - cron: '0 6-15 * * *'
  workflow_dispatch: # Manuel test için

jobs:
  send-report:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: g_portal-main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Send daily report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: node scripts/send-daily-report.js
